opt_dataset:
  fineSize: 256
  augment_fn: histo
  use_color: gray
  crop: False
  name: breakhis
  source_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/breakhis/fold1/source.csv
  target_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/breakhis/fold1/target.csv
  test_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/breakhis/fold1/test.csv
  train_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/breakhis/fold1/train.csv
  P_mask: /home/congz3414050/cong/CAGAN_Stain_Norm/results/visuals/breakhis_2.png
  image_index: 0
  label_index: 1
  num_class: 2