opt_dataset:
  fineSize: 256
  augment_fn: histo
  use_color: gray
  crop: False
  name: cam16
  source_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/CAMELYON16/train/source.csv
  target_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/CAMELYON16/train/target.csv
  test_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/CAMELYON16/test/test.csv
  train_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/CAMELYON16/train/train.csv
  P_mask: /home/congz3414050/cong/CAGAN_Stain_Norm/results/visuals/cam16_2.png
  image_index: 0
  label_index: 1
  num_class: 2